{
    'name': "DAT TechService Ticket Management",
    'version': '17.0.1.0.5',
    'category': 'Website',
    'summary': "Module for managing tickets in DAT TechService",
    'description': """
    This module provides a ticket management system for DAT TechService,
    allowing users to create, track, and resolve service tickets efficiently.
    """,
    'author': "DAT Group",
    'company': 'DAT Group',
    'maintainer': 'DAT Group',
    'depends': ['website', 'sale', 'hr_timesheet', 'mail', 'contacts', 'stock', 'dat_zalo_zns', 'dat_sap_config', 'core_fastapi', 'base_automation', 'dat_notification_management', 'dms'],
    'data': [
        'security/dat_website_helpdesk_groups.xml',
        'security/dat_website_helpdesk_security.xml',
        'security/hr_security.xml',
        'security/ir.model.access.csv',
        'data/ticket_step_data.xml',
        'data/res_currency_data.xml',
        'data/res_company_data.xml',
        'data/stock_warehouse_data.xml',
        'data/hr_demo.xml',
        'data/helpdesk_workflow_data.xml',
        'data/helpdesk_type_data.xml',
        'data/res_users_data.xml',
        'data/ir_sequence_data.xml',
        'data/ticket_priority_data.xml',
        'data/zalo_zns_template_data.xml',
        'data/zalo_zns_template_param_data.xml',
        'data/implementation_work_data.xml',
        'data/notification_template_data.xml',
        'data/base_automationd_data.xml',
        'data/ticket_io_range_data.xml',
        'views/helpdesk_assignment_follower_view.xml',
        'views/public_homepage_templates.xml',
        'views/portal_templates.xml',
        'views/res_company_views.xml',
        'views/sale_order_views.xml',
        'views/ticket_product_image_views.xml',
        'views/helpdesk_type_views.xml',
        'views/helpdesk_workflow_views.xml',
        'views/dat_website_helpdesk_portal_templates.xml',
        'views/ticket_priority_views.xml',
        'views/ticket_io_range_views.xml',
        'views/helpdesk_assignment_mapping_view.xml',
        'views/rating_form.xml',
        'views/zalo_zns_message_views.xml',
        'views/product_product_views.xml',
        'views/stock_warehouse.xml',
        'wizard/ticket_reject_wizard_views.xml',
        'wizard/ticket_on_hold_wizard_views.xml',
        'wizard/ticket_return_step_wizard_views.xml',
        'wizard/ticket_reassign_wizard_views.xml',
        'wizard/create_ticket_wizard_views.xml',
        'report/helpdesk_ticket_report_template.xml',
        'views/res_config_settings_views.xml',
        'views/ticket_helpdesk_views.xml',
        'views/ticket_step_views.xml',
        'views/website_form.xml',
        'views/implementation_work_template_views.xml',
        'views/helpdesk_error_views.xml',
        'views/helpdesk_views.xml',
        'views/stock_lot_views.xml',
        'views/res_partner_views.xml',
        'views/dat_opportunity_views.xml',
        'views/website_template.xml',
        'views/sale_order_sap_batch_action.xml',
        'wizard/ticket_error_delete_wizard_views.xml',        
        'views/ticket_external_document_views.xml',
    ],
    'assets': {
        'web._assets_primary_variables': [
            'dat_website_helpdesk/static/src/css/variables.scss',
        ],
        'web.assets_frontend': [
            '/dat_website_helpdesk/static/src/js/multiple_product_choose.js',
            '/dat_website_helpdesk/static/src/css/style.scss',
            '/dat_website_helpdesk/static/src/css/my_home.scss',
            '/dat_website_helpdesk/static/src/css/create_ticket.scss',
            '/dat_website_helpdesk/static/src/css/custom_searchbar.scss',
            '/dat_website_helpdesk/static/src/css/custom_footer.scss',
            '/dat_website_helpdesk/static/src/css/table_sorting.scss',
            "dat_website_helpdesk/static/src/js/table_sorting.js",
            "dat_website_helpdesk/static/src/js/slider_image.js",
            "dat_website_helpdesk/static/src/css/slider_image.scss"
        ],
        'web.assets_backend': [
            "dat_website_helpdesk/static/src/css/style.scss",
            "dat_website_helpdesk/static/src/views/dat_helpdesk_list_buttons.xml",
            "dat_website_helpdesk/static/src/views/dat_helpdesk_list_controller.js",
            "dat_website_helpdesk/static/src/views/dat_helpdesk_list_view.js",
            "dat_website_helpdesk/static/src/js/form_controller.js",
            "dat_website_helpdesk/static/src/model/relational_model/record.js",
            "dat_website_helpdesk/static/src/js/messaging_menu_inherit.js"
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
