{
    'name': 'DAT Zalo ZNS Integration',
    'version': '17.0.1.0.5',
    'category': 'Marketing',
    'summary': 'Module for managing Zalo ZNS templates and send messages in DAT TechService',
    'author': "DAT Group",
    'company': 'DAT Group',
    'maintainer': 'DAT Group',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/zalo_zns_config_views.xml',
        'views/zalo_zns_template_views.xml',
        'views/zalo_zns_batch_views.xml',
        'views/zalo_zns_message_views.xml',
        'views/zalo_zns_recipient_views.xml',
        'views/zalo_zns_menu.xml',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
