from . import dat_opportunity
from . import dat_opportunity_activity
from . import fastapi_endpoint
from . import helpdesk_type
from . import helpdesk_workflow
from . import mail_compose_message
from . import res_config_settings
from . import res_partner
from . import product_product
from . import sale_order
from . import sale_order_line
from . import stock_lot
from . import ticket_io_range
from . import helpdesk_assignment_mapping
from . import ticket_helpdesk_assignment_follower
from . import stock_warehouse
from . import ticket_helpdesk
from . import ticket_priority
from . import ticket_step
from . import website_menu
from . import ticket_product_image
from . import res_company
from . import ir_sequence
from . import hr_department
from . import ir_attachment
from . import implementation_work
from . import ticket_step_assignee
from . import ticket_helpdesk_error
from . import ticket_board_serial_line
from . import ticket_rating
from . import zalo_zns_message
from . import ticket_external_document
