from . import abstract_sync_sap
from . import ir_cron
from . import ir_cron_history
from . import product_category
from . import product_product
from . import product_template
from . import res_config_settings
from . import resource_calendar_attendance
from . import uom_uom
from . import sale_order
from . import technical_proposal
from . import hr_employee
from . import res_partner
from . import stock_lot
from . import ticket_helpdesk
