{
    'name': "DAT Dashboard",
    'version': '17.0.1.0.9',
    'category': 'Productivity',
    'summary': """Create Configurable Dashboards Easily""",
    'description': """Odoo Dynamic Dashboard, Dynamic Dashboard, Odoo Dashboard, Web Dynamic Dashboard, Dashboard with AI, Analytic Dashboard, AI Dashboard, Odoo17 Dashboard, Responsive Dashboard, Odoo17, Dashboard""",
    'author': "DAT Group",
    'company': 'DAT Group',
    'maintainer': 'DAT Group',
    'depends': ['dat_helpdesk_steps_sla', 'dat_product', 'base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'views/dashboard_views.xml',
        'views/dynamic_block_views.xml',
        'views/dashboard_theme_views.xml',
        'wizard/dashboard_mail_views.xml',
        'wizard/repair_sales_wizard_views.xml',
        'wizard/repair_warranty_wizard_views.xml',
        'wizard/step_provide_tech_wizard_views.xml',
        'wizard/survey_research_time_wizard_views.xml',
        'wizard/solution_design_points_wizard_views.xml',
        'wizard/step_sla_compliance_wizard_views.xml',
        # 'wizard/ticket_kpi_wizard_wf3_views.xml',
        'data/dashboard_theme_data.xml',
        'data/dashboard_report_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dat_dashboard/static/src/css/**/*.css',
            'dat_dashboard/static/src/scss/**/*.scss',
            'dat_dashboard/static/src/js/**/*.js',
            'dat_dashboard/static/src/xml/**/*.xml',
            'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css',
            'dat_dashboard/static/library/js/interactjs.js',
        ],
    },
    'license': "LGPL-3",
    'installable': True,
    'auto_install': False,
    'application': True,
}
