{
    'name': "DAT TechService Ticket Management Steps SLA",
    'version': '17.0.1.0.55',
    'category': 'Website',
    'summary': """SLA""",
    'description': """SLA""",
    'author': "DAT Group",
    'company': 'DAT Group',
    'maintainer': 'DAT Group',
    'depends': ['dat_website_helpdesk'],
    'data': [
        'security/ir.model.access.csv',
        'security/dat_helpdesk_steps_sla_security.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'views/helpdesk_workflow_views.xml',
        'views/ticket_step_views.xml',
        'views/ticket_helpdesk_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': True,
    'application': False,
}
